#Numpy - Numerical Python

- used for array operations, linear algebra , statistics, and more

In [1]:
!pip install numpy

#pip - python installing packge

In [4]:
import numpy as np

#as - alias - nickname

In [8]:
list1 = [10,20,30]

In [9]:
a = np.array(list1)

In [10]:
a

array([10, 20, 30])

In [11]:
#2d array

In [12]:
b = np.array([[10,20], [40,50]])

In [13]:
b

array([[10, 20],
       [40, 50]])

In [16]:
c = np.array([[[1,2], [3,4]],    [[5,6],[7,8]]])

In [17]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#attributes

In [18]:
#check the dimentions - .ndim

In [19]:
a.ndim

1

In [20]:
b.ndim

2

In [21]:
c.ndim

3

In [25]:
d = np.array([[[1,2]]])

In [26]:
d.ndim

3

In [27]:
#.shape

In [28]:
a.shape

(3,)

In [29]:
b.shape

(2, 2)

In [30]:
c.shape

(2, 2, 2)

In [31]:
d.shape

(1, 1, 2)

In [32]:
d

array([[[1, 2]]])

In [33]:
arr = np.array([[1,2,3],[4,5,6]])

In [34]:
arr.shape

(2, 3)

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
#.size

In [44]:
arr.size

6

In [46]:
#.dtype

In [47]:
arr.dtype

dtype('int64')

In [48]:
arr1 =np.array([40,50,60], dtype= np.int16)

In [49]:
arr1

array([40, 50, 60], dtype=int16)

- int - whole no - int8, int16, int32, int64
- only positive - unsigned int - np.uint8, np.uint16, 32,
- float - decimal - float16, 32,64
- bool - True Flase - np.bool_
- string - np.str_
- Object - Mix Data Type - np.object_

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr.T   # .T traspose the array

array([[1, 4],
       [2, 5],
       [3, 6]])

#methods

In [53]:
# np.random.rand()  - random float create between 0 to 1

In [55]:
np.random.rand()

0.8464012604057629

In [56]:
np.random.rand(3)

array([0.19059563, 0.31206818, 0.3118222 ])

In [58]:
np.random.rand(2,3)

array([[0.07311772, 0.6184363 , 0.1129634 ],
       [0.62302066, 0.23822032, 0.22832887]])

In [59]:
#np.random.randn()  - create standard normal distribution
#where mean always = 0 and standerd deviation = 1

In [60]:
np.random.randn(5)

array([-0.59698188,  0.41910758,  1.08159161, -1.84081722, -0.98803695])

In [61]:
np.random.randn(3,2)

array([[-0.6855877 ,  1.11611661],
       [ 0.12776195, -1.75337517],
       [ 0.86865318,  1.51456433]])

In [62]:
#random.randint()

In [70]:
np.random.randint(1,7)  #single random element betwn 1 to 6

5

In [75]:
np.random.randint(10)  #start from 0 to 9

8

In [82]:
np.random.randint(10, size=5)  #range 0 to 9

array([2, 8, 9, 9, 9])

# indexing and slicing

In [83]:
arr = np.array([10,20,30,40,50,60])

In [91]:
print(arr[-1])

60


In [89]:
arr1= np.array([[10,20,30], [90,80,70]])

In [90]:
arr1

array([[10, 20, 30],
       [90, 80, 70]])

In [92]:
print(arr1[0][1])

20


In [93]:
print(arr1[1][2])

70


In [94]:
#slicing

In [95]:
print(arr1[1,2])

70


In [99]:
print(arr1[0:2,1:3])

[[20 30]
 [80 70]]


In [97]:
arr1

array([[10, 20, 30],
       [90, 80, 70]])

#aggrigation functions

In [100]:
arr1

array([[10, 20, 30],
       [90, 80, 70]])

In [102]:
print(np.sum(arr1))

300


In [103]:
print(np.mean(arr1))

50.0


In [106]:
print(np.min(arr1))

10


In [107]:
print(np.std(arr1))  #standerd deviation

31.09126351029605


In [108]:
print(np.var(arr1))  #variance

966.6666666666666


In [109]:
#.reshape

In [110]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [111]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr = np.array([1,2,3,4,5,6])

In [113]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])